import "dotenv/config";
import express from "express";
import cors from "cors";
import multer from "multer";
import fs from "node:fs/promises";
import path from "node:path";
import http from "node:http";
import { WebSocketServer, WebSocket as WSWebSocket } from "ws";
import { chat } from "./llm.js";
import { paperclip } from "./paperclip.js";
import type { RequirementParams } from "./types.js";
import { routeFile, uniqueName, requirementsDir, type Hint } from "./services/fileRouter.js";
import { writeTranscript } from "./services/transcriptWriter.js";
import { transcribeAudioFile } from "./services/geminiFiles.js";
import { MeetingSession } from "./services/geminiLive.js";

const app = express();
app.use(cors());
app.use(express.json({ limit: "10mb" }));

// 1. Chat — proxy to Gemini. `target` (optional) is the current target picker
//    selection in the UI; we forward it so the LLM stops re-asking when the
//    user has already selected a project/feature.
app.post("/api/chat", async (req, res) => {
  try {
    const { messages, target } = req.body;
    const result = await chat(messages, target);
    res.json(result);
  } catch (e: any) {
    console.error(e);
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});

// 2. Trigger — create a Paperclip issue from a parameter bundle
app.post("/api/trigger", async (req, res) => {
  try {
    const overrides = (req.body ?? {}) as Partial<RequirementParams> & {
      feature_name?: string;
      project?: string;
      feature?: string;
    };
    const feature_name = overrides.feature_name || process.env.DEFAULT_FEATURE_NAME || "Untitled Feature";
    const project = overrides.project || "SADA";
    const feature = overrides.feature || "interim-benefit";
    const params: RequirementParams = {
      process_l3: overrides.process_l3 || process.env.DEFAULT_PROCESS_L3,
      process_l4: overrides.process_l4 || process.env.DEFAULT_PROCESS_L4,
      starting_story_number: overrides.starting_story_number || process.env.DEFAULT_STARTING_STORY_NUMBER,
      parent_epic_key: overrides.parent_epic_key || process.env.DEFAULT_PARENT_EPIC_KEY,
      jira_project_key: overrides.jira_project_key || process.env.DEFAULT_JIRA_PROJECT_KEY,
      confluence_space_key: overrides.confluence_space_key || process.env.DEFAULT_CONFLUENCE_SPACE_KEY,
      confluence_page_title: overrides.confluence_page_title || process.env.DEFAULT_CONFLUENCE_PAGE_TITLE,
    };
    const ws = process.env.WORKSPACE_PATH || "/Users/tagariwalayashesh/Projects/buzzinga/requirement-generator";
    const description = [
      `Generated by the Scyne chatbot. Please produce the Product Summary and Jira user stories.`,
      ``,
      `## Project + Feature`,
      `- Project: ${project}`,
      `- Feature: ${feature}`,
      ``,
      `## Parameters`,
      `- Process L3: ${params.process_l3}`,
      `- Process L4: ${params.process_l4}`,
      `- Starting story number: ${params.starting_story_number}`,
      `- Parent epic key: ${params.parent_epic_key}`,
      `- Jira project key: ${params.jira_project_key}`,
      `- Confluence space key: ${params.confluence_space_key}`,
      `- Confluence page title: ${params.confluence_page_title}`,
      ``,
      `## Inputs`,
      `Read every file in every subfolder of:`,
      `\`${ws}/projects/${project}/${feature}/requirements/\``,
      ``,
      `Subfolders: Policy/, Transcripts/, Notes/, UI/.`,
    ].join("\n");

    const issue = await paperclip.createIssue(
      `Generate requirements — ${feature_name} (${project}/${feature})`,
      description
    );
    res.json(issue);
  } catch (e: any) {
    console.error(e);
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});

// 3. Status — normalized progress view: tree + computed stage + activity timeline + extracted links + approvals
app.get("/api/status/:issueId", async (req, res) => {
  try {
    const id = req.params.issueId;
    const tree = await paperclip.getIssueTree(id);

    // Flatten all comments + approvals + work-products from parent + descendants
    const flatIssues: any[] = [];
    const flatComments: any[] = [];
    const flatApprovals: any[] = [];
    const workProductsByIssue: Record<string, any[]> = {};

    function walk(node: any) {
      flatIssues.push({
        id: node.id,
        identifier: node.identifier,
        title: node.title,
        status: node.status,
        assigneeAgentId: node.assigneeAgentId,
        createdAt: node.createdAt,
        updatedAt: node.updatedAt,
      });
      for (const c of node.comments ?? []) {
        flatComments.push({
          id: c.id,
          issueId: node.id,
          issueIdentifier: node.identifier,
          body: c.body ?? c.content ?? "",
          author: c.authorAgentName ?? c.authorUserName ?? c.authorAgentId ?? c.authorUserId ?? "system",
          createdAt: c.createdAt,
        });
      }
      for (const a of node.approvals ?? []) {
        const payload = (a.payload ?? {}) as Record<string, any>;
        flatApprovals.push({
          id: a.id,
          issueId: node.id,
          issueIdentifier: node.identifier,
          title: payload.title ?? a.title ?? "Approval requested",
          description: payload.summary ?? payload.description ?? payload.recommendedAction ?? a.description ?? "",
          status: a.status ?? null, // "pending" | "approved" | "rejected" | "revision_requested" | "cancelled"
          createdAt: a.createdAt,
          resolvedAt: a.decidedAt ?? a.resolvedAt ?? null,
          decisionNote: a.decisionNote ?? null,
        });
      }
      workProductsByIssue[node.id] = node.workProducts ?? [];
      for (const child of node.children ?? []) walk(child);
    }
    walk(tree);

    // Sort comments by createdAt ascending so they read like a timeline
    flatComments.sort((a, b) => String(a.createdAt).localeCompare(String(b.createdAt)));

    // Extract URLs from all comments
    const confluenceRe = /https?:\/\/[\w.-]+\.atlassian\.net\/wiki\/[^\s)>\]"']+/g;
    const jiraRe = /https?:\/\/[\w.-]+\.atlassian\.net\/browse\/[A-Z]+-\d+/g;
    const confluenceSet = new Set<string>();
    const jiraSet = new Set<string>();
    for (const c of flatComments) {
      const body = String(c.body);
      for (const m of body.matchAll(confluenceRe)) confluenceSet.add(m[0]);
      for (const m of body.matchAll(jiraRe)) jiraSet.add(m[0]);
    }
    const links = {
      confluence: [...confluenceSet],
      jira: [...jiraSet].sort(),
    };

    // Derive a coarse current "stage" from the state of the tree
    const parent = flatIssues[0];
    const children = flatIssues.slice(1);
    const anyApproved = flatApprovals.some((a) => a.status === "approved");
    const anyPending = flatApprovals.some((a) => !a.status || a.status === "pending");
    const allDone = flatIssues.length > 0 && flatIssues.every((i) => i.status === "done");
    let stage: { key: string; label: string };
    if (allDone) stage = { key: "done", label: "Complete" };
    else if (anyApproved && !allDone) stage = { key: "pushing", label: "Pushing to Atlassian" };
    else if (anyPending) stage = { key: "awaiting_approval", label: "Awaiting your approval" };
    else if (children.some((c) => c.status === "in_progress" || c.status === "in_review")) stage = { key: "ba_generating", label: "BA generating artifacts" };
    else if (children.length > 0) stage = { key: "delegated", label: "Delegated to BA" };
    else if (parent?.status === "in_progress") stage = { key: "pm_triaging", label: "PM triaging the request" };
    else stage = { key: "queued", label: "Queued" };

    res.json({
      tree,
      stage,
      flatIssues,
      activity: flatComments,
      approvals: flatApprovals,
      workProducts: workProductsByIssue,
      links,
    });
  } catch (e: any) {
    console.error(e);
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});

// 4. Approve — proxy approval decision
app.post("/api/approve/:approvalId", async (req, res) => {
  try {
    const r = await paperclip.approveGate(req.params.approvalId, req.body?.note);
    res.json(r);
  } catch (e: any) {
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});

app.post("/api/reject/:approvalId", async (req, res) => {
  try {
    const r = await paperclip.rejectGate(req.params.approvalId, req.body?.note);
    res.json(r);
  } catch (e: any) {
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});


// 5. List available projects + features by scanning the workspace
app.get("/api/features", async (_req, res) => {
  try {
    const fs = await import("node:fs/promises");
    const path = await import("node:path");
    const ws = process.env.WORKSPACE_PATH || "/Users/tagariwalayashesh/Projects/buzzinga/requirement-generator";
    const projectsDir = path.join(ws, "projects");
    const result: Record<string, { name: string; counts: Record<string, number> }[]> = {};
    try {
      const projects = await fs.readdir(projectsDir, { withFileTypes: true });
      for (const p of projects) {
        if (!p.isDirectory()) continue;
        const features = await fs.readdir(path.join(projectsDir, p.name), { withFileTypes: true });
        result[p.name] = [];
        for (const s of features) {
          if (!s.isDirectory()) continue;
          const subPath = path.join(projectsDir, p.name, s.name);
          const subs = await fs.readdir(subPath, { withFileTypes: true });
          const counts: Record<string, number> = {};
          for (const sub of subs) {
            if (!sub.isDirectory()) continue;
            const files = await fs.readdir(path.join(subPath, sub.name));
            counts[sub.name] = files.length;
          }
          result[p.name].push({ name: s.name, counts });
        }
      }
    } catch (e) {
      // No projects/ dir yet — return empty
    }
    res.json(result);
  } catch (e: any) {
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});


// 6. Artefacts — read the BA's generated outputs from disk so the UI can preview before approval
app.get("/api/artifacts", async (_req, res) => {
  try {
    const fs = await import("node:fs/promises");
    const path = await import("node:path");
    const ws = process.env.WORKSPACE_PATH || "/Users/tagariwalayashesh/Projects/buzzinga/requirement-generator";
    const outputs = path.join(ws, "outputs");
    const read = async (f: string) => {
      try { return await fs.readFile(path.join(outputs, f), "utf8"); } catch { return null; }
    };
    const [productSummary, storiesJson, storiesMd, gaps] = await Promise.all([
      read("product-summary.md"),
      read("stories.json"),
      read("stories.md"),
      read("gaps.md"),
    ]);
    let stories: any[] = [];
    if (storiesJson) {
      try {
        const parsed = JSON.parse(storiesJson);
        stories = (Array.isArray(parsed) ? parsed : []).map((s: any) => ({
          summary: s?.fields?.summary ?? "",
          description: s?.fields?.description ?? "",
          labels: s?.fields?.labels ?? [],
          meta: s?._meta ?? {},
        }));
      } catch {}
    }
    res.json({ productSummary, stories, storiesMd, gaps });
  } catch (e: any) {
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});

// --- Uploads & voice agent ------------------------------------------------

const WORKSPACE_PATH = process.env.WORKSPACE_PATH || "/Users/tagariwalayashesh/Projects/buzzinga/requirement-generator";
const SAFE_NAME = /^[A-Za-z0-9._-]+$/;
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 100 * 1024 * 1024 }, // 100 MB
});

function assertSafeProjectFeature(project: string, feature: string) {
  if (!SAFE_NAME.test(project) || !SAFE_NAME.test(feature)) {
    const err: any = new Error("Invalid project or feature name");
    err.status = 400;
    throw err;
  }
}

// 7. Upload a single file — auto-route into projects/<project>/<feature>/<subfolder>/.
//    Audio files (.mp3/.wav/.m4a/...) are transcribed via Gemini Files API and
//    written as transcript-upload-N.md inside transcripts/.
app.post("/api/upload", upload.single("file"), async (req, res) => {
  try {
    const project = String(req.body?.project || "").trim();
    const feature = String(req.body?.feature || "").trim();
    const hint = (req.body?.hint as Hint) || undefined;
    if (!project || !feature) return res.status(400).json({ error: "project and feature are required" });
    assertSafeProjectFeature(project, feature);
    if (!req.file) return res.status(400).json({ error: "file is required (field name: 'file')" });

    const route = routeFile(req.file.originalname, hint);

    // Ambiguous .docx/.pdf — caller must resupply with hint.
    if (route.ambiguous && !hint) {
      return res.status(409).json({
        error: "ambiguous_kind",
        message: `Couldn't infer where ${req.file.originalname} belongs. Hint with one of: policy, transcripts, notes.`,
        originalName: req.file.originalname,
      });
    }

    if (route.isAudio) {
      const transcribed = await transcribeAudioFile(
        await spillToTemp(req.file.buffer, req.file.originalname),
        req.file.mimetype || "audio/mpeg",
      );
      if (transcribed.entries.length === 0) {
        return res.status(422).json({ error: "no_transcript", message: "Gemini returned no transcript text", raw: transcribed.rawText });
      }
      const result = await writeTranscript({
        project,
        feature,
        workspace: WORKSPACE_PATH,
        source: "audio-upload",
        entries: transcribed.entries,
        originalFilename: req.file.originalname,
      });
      return res.json({
        kind: "transcript",
        subfolder: "transcripts",
        filename: result.filename,
        relativePath: result.relativePath,
        entryCount: transcribed.entries.length,
        modelUsed: transcribed.modelUsed,
      });
    }

    const targetDir = requirementsDir(WORKSPACE_PATH, project, feature, route.subfolder);
    await fs.mkdir(targetDir, { recursive: true });
    const savedName = await uniqueName(targetDir, route.savedName);
    await fs.writeFile(path.join(targetDir, savedName), req.file.buffer);
    return res.json({
      kind: "file",
      subfolder: route.subfolder,
      filename: savedName,
      relativePath: path.relative(WORKSPACE_PATH, path.join(targetDir, savedName)),
    });
  } catch (e: any) {
    console.error("[upload] failed:", e);
    res.status(e?.status ?? 500).json({ error: e?.message ?? String(e) });
  }
});

// 7a. Trigger a UI build — creates a PM-assigned issue with the "Build UI — ..." title.
//     PM detects this intent, validates outputs/product-summary.md exists, then dispatches
//     the UI Engineer directly (its direct report). When the UI Engineer finishes, PM is
//     auto-woken (issue_children_completed) and dispatches the UX Auditor — both report to PM.
app.post("/api/ui-agent/trigger", async (req, res) => {
  try {
    const project = String(req.body?.project || "").trim();
    const feature = String(req.body?.feature || "").trim();
    if (!project || !feature) return res.status(400).json({ error: "missing_target", message: "project and feature are required" });
    assertSafeProjectFeature(project, feature);

    // Quick local check so we can fail fast with a clear error in the chat.
    const summaryPath = path.join(WORKSPACE_PATH, "projects", project, feature, "outputs", "product-summary.md");
    try {
      await fs.access(summaryPath);
    } catch {
      return res.status(409).json({
        error: "no_requirements",
        message: `No requirements found for ${project}/${feature}. Run the BA flow first, or drop a product-summary.md under outputs/.`,
      });
    }

    const title = `Build UI — ${project}/${feature}`;
    const description = [
      `project: ${project}`,
      `feature: ${feature}`,
      `intent: build_ui`,
      ``,
      `Inputs:`,
      `- projects/${project}/${feature}/design/style-guides/`,
      `- projects/${project}/${feature}/design/example-screens/`,
      `- projects/${project}/${feature}/outputs/product-summary.md`,
      `- projects/${project}/${feature}/outputs/stories.json`,
    ].join("\n");

    // Assigned to PM (existing pattern). PM dispatches the UI Engineer directly, then the UX Auditor.
    const issue = await paperclip.createIssue(title, description);
    res.json(issue);
  } catch (e: any) {
    console.error("[ui-agent/trigger] failed:", e);
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});

// 7b. Preview registry lookup for the iframe pane.
app.get("/api/preview/:project/:feature", async (req, res) => {
  try {
    const { project, feature } = req.params;
    assertSafeProjectFeature(project, feature);
    const registryPath = path.join(WORKSPACE_PATH, "generated-apps", "registry.json");
    let registry: Record<string, any> = {};
    try {
      registry = JSON.parse(await fs.readFile(registryPath, "utf8"));
    } catch {
      return res.status(404).json({ error: "no_registry" });
    }
    const entry = registry[`${project}-${feature}`];
    if (!entry) return res.status(404).json({ error: "no_entry" });
    res.json(entry);
  } catch (e: any) {
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});

// 7c. Thin comment relay. The frontend reads the issue tree via /api/status/<parent>
//     and identifies the UI child issue (title starts with "Build UI"). It passes that
//     issueId here. We just post the comment — no agent-id filtering, no env vars.
app.post("/api/ui-agent/comment", async (req, res) => {
  try {
    const issueId = String(req.body?.issueId || "").trim();
    const body = String(req.body?.body || "").trim();
    if (!issueId || !body) {
      return res.status(400).json({ error: "issueId and body are required" });
    }
    await paperclip.addComment(issueId, body);
    res.json({ ok: true, issueId });
  } catch (e: any) {
    console.error("[ui-agent/comment] failed:", e);
    res.status(500).json({ error: e?.message ?? String(e) });
  }
});

async function spillToTemp(buffer: Buffer, name: string): Promise<string> {
  const os = await import("node:os");
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "scyne-upload-"));
  const p = path.join(dir, name.replace(/[^A-Za-z0-9._-]/g, "_") || "audio.bin");
  await fs.writeFile(p, buffer);
  return p;
}

const PORT = Number(process.env.PORT) || 4000;
const server = http.createServer(app);

// 8. WebSocket — live meeting recording.
//    Protocol (JSON messages over the same socket):
//      browser → server: { type: "start", project, feature }
//      browser → server: { type: "audio", data: <base64 16kHz mono PCM> }
//      browser → server: { type: "stop" }
//      server → browser: { type: "ready" }
//      server → browser: { type: "transcript_delta", speaker, text, timestampSec }
//      server → browser: { type: "transcript_done", speaker }
//      server → browser: { type: "saved", relativePath, filename, entryCount, durationSeconds }
//      server → browser: { type: "error", message }
const wss = new WebSocketServer({ server, path: "/ws/record" });

wss.on("connection", (ws: WSWebSocket) => {
  let session: MeetingSession | null = null;
  let project: string | null = null;
  let feature: string | null = null;
  let finalising = false;

  const send = (msg: any) => {
    if (ws.readyState === ws.OPEN) ws.send(JSON.stringify(msg));
  };

  ws.on("message", async (raw) => {
    let msg: any;
    try { msg = JSON.parse(raw.toString()); } catch { return; }

    try {
      if (msg.type === "start") {
        if (session) return;
        project = String(msg.project || "").trim();
        feature = String(msg.feature || "").trim();
        if (!project || !feature) {
          send({ type: "error", message: "project and feature are required" });
          return;
        }
        assertSafeProjectFeature(project, feature);
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
          send({ type: "error", message: "GEMINI_API_KEY is not set on the server" });
          return;
        }
        session = new MeetingSession({
          apiKey,
          onEvent: (e) => send(e),
        });
        try {
          await session.start();
        } catch (err: any) {
          send({ type: "error", message: `Failed to open Gemini Live: ${err?.message ?? err}` });
          session = null;
        }
        return;
      }

      if (msg.type === "audio") {
        if (!session) return;
        if (typeof msg.data !== "string") return;
        session.sendAudio(msg.data);
        return;
      }

      if (msg.type === "stop") {
        if (!session || finalising) return;
        finalising = true;
        await finaliseSession();
        return;
      }
    } catch (err: any) {
      send({ type: "error", message: err?.message ?? String(err) });
    }
  });

  ws.on("close", async () => {
    if (session && !finalising) {
      finalising = true;
      try { await finaliseSession(); } catch { /* ignore */ }
    }
    if (session) {
      try { session.close(); } catch { /* ignore */ }
      session = null;
    }
  });

  async function finaliseSession() {
    if (!session || !project || !feature) return;
    const entries = session.getEntries();
    const duration = session.getDurationSeconds();
    session.close();
    if (entries.length === 0) {
      send({ type: "saved", relativePath: null, filename: null, entryCount: 0, durationSeconds: duration, empty: true });
      return;
    }
    try {
      const result = await writeTranscript({
        project,
        feature,
        workspace: WORKSPACE_PATH,
        source: "live-recording",
        entries,
        durationSeconds: duration,
      });
      send({
        type: "saved",
        relativePath: result.relativePath,
        filename: result.filename,
        entryCount: entries.length,
        durationSeconds: duration,
      });
    } catch (err: any) {
      send({ type: "error", message: `Failed to save transcript: ${err?.message ?? err}` });
    }
  }
});

server.listen(PORT, () => {
  console.log(`Scyne chatbot API listening on http://127.0.0.1:${PORT}`);
  console.log(`Live recording WebSocket at ws://127.0.0.1:${PORT}/ws/record`);
});
